### ISSUE TITLE
`0.1.0` release checklist

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/epinowcast#92]
This issue summarises the work needed ahead of the release of `0.1.0` which is aiming to be a the last release (at least for the moment) with major breaking changes. 

- [ ] #82 
- [ ] #71 
- [ ] #78 
- [ ] #57 
- [ ] #5 
- [ ] #3 
- [ ] #4 
- [ ] #72 
- [ ] #43 
- [ ] Rerun and render README
- [ ] Rerun examples
- [ ] Rerun vignettes
- [ ] Update news
- [ ] Make a Github release of `0.0.7`
- [ ] Make a PR for `0.1.0`
- [ ] Make a GitHub release for `0.1.0`
- [ ] Make a twitter thread

**Comment by seabbs** [comment]
Dropped major features from the release.

**Comment by seabbs** [comment]
Then we can get on to the exciting feature updates, make the model so fancy (also more postprocessing and prior customisation but less exciting), and make handling data super easy and fun.
